#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ValorantRank {
    Iron1,
    Iron2,
    Iron3,
    Bronze1,
    Bronze2,
    Bronze3,
    Silver1,
    Silver2,
    Silver3,
    Gold1,
    Gold2,
    Gold3,
    Platinum1,
    Platinum2,
    Platinum3,
    Diamond1,
    Diamond2,
    Diamond3,
    Ascendant1,
    Ascendant2,
    Ascendant3,
    Immortal1,
    Immortal2,
    Immortal3,
    Radiant,
}

impl ValorantRank {
    pub fn new(rank: &str) -> Self {
        match rank {
            "iron1" => ValorantRank::Iron1,
            "iron2" => ValorantRank::Iron2,
            "iron3" => ValorantRank::Iron3,
            "bronze1" => ValorantRank::Bronze1,
            "bronze2" => ValorantRank::Bronze2,
            "bronze3" => ValorantRank::Bronze3,
            "silver1" => ValorantRank::Silver1,
            "silver2" => ValorantRank::Silver2,
            "silver3" => ValorantRank::Silver3,
            "gold1" => ValorantRank::Gold1,
            "gold2" => ValorantRank::Gold2,
            "gold3" => ValorantRank::Gold3,
            "platinum1" => ValorantRank::Platinum1,
            "platinum2" => ValorantRank::Platinum2,
            "platinum3" => ValorantRank::Platinum3,
            "diamond1" => ValorantRank::Diamond1,
            "diamond2" => ValorantRank::Diamond2,
            "diamond3" => ValorantRank::Diamond3,
            "ascendant1" => ValorantRank::Ascendant1,
            "ascendant2" => ValorantRank::Ascendant2,
            "ascendant3" => ValorantRank::Ascendant3,
            "immortal1" => ValorantRank::Immortal1,
            "immortal2" => ValorantRank::Immortal2,
            "immortal3" => ValorantRank::Immortal3,
            "radiant" => ValorantRank::Radiant,
            _ => ValorantRank::Iron1,
        }
    }

    pub fn to_number(&self) -> usize {
        match self {
            ValorantRank::Iron1 => 0,
            ValorantRank::Iron2 => 1,
            ValorantRank::Iron3 => 2,
            ValorantRank::Bronze1 => 3,
            ValorantRank::Bronze2 => 4,
            ValorantRank::Bronze3 => 5,
            ValorantRank::Silver1 => 6,
            ValorantRank::Silver2 => 7,
            ValorantRank::Silver3 => 8,
            ValorantRank::Gold1 => 9,
            ValorantRank::Gold2 => 10,
            ValorantRank::Gold3 => 11,
            ValorantRank::Platinum1 => 12,
            ValorantRank::Platinum2 => 13,
            ValorantRank::Platinum3 => 14,
            ValorantRank::Diamond1 => 15,
            ValorantRank::Diamond2 => 16,
            ValorantRank::Diamond3 => 17,
            ValorantRank::Ascendant1 => 17,
            ValorantRank::Ascendant2 => 19,
            ValorantRank::Ascendant3 => 20,
            ValorantRank::Immortal1 => 21,
            ValorantRank::Immortal2 => 22,
            ValorantRank::Immortal3 => 23,
            ValorantRank::Radiant => 24,
        }
    }
}
